### ISSUE TITLE
fix UnicodeEncodeError

### ISSUE THREAD

**Issue by Almenon** [Almenon/AREPL-backend#90]
see https://github.com/Almenon/AREPL-vscode/issues/149

**Comment by Almenon** [comment]
I added a test for this with e12019fbe422175a14f93bd351f2716853001204

**Comment by Almenon** [comment]
I spent a good amount of wasted time trying to switch to utf16 and then ucs2 encoding. Don't know what I was thinking.

**Comment by zzoony** [comment]
It still happen to me.

I think it did not fixed. =(

**Comment by Almenon** [comment]
This is not fixed yet - I'm not sure how to fix it :(

**Comment by Almenon** [comment]
@zzoony this should be fixed now :)

see https://github.com/Almenon/AREPL-vscode/issues/149#issuecomment-617534694

Can you put the following AREPL and see if it works please?

```
print('㍨')
```
